version: "3"

services:

  redis:
    image: redis:alpine

  db:
    image: sameersbn/postgresql:9.6-2
    ports:
      - "15432:5432"
    environment:
      - "PG_PASSWORD=123456"
    volumes:
      - .data-docker/postgresql:/var/lib/postgresql

  # object storage
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    command:
      - server
      - /data
    environment:
    # hard-coded access keys for easy debugging
      - "MINIO_ACCESS_KEY=HJW6280KHBS2Y105STGG"
      - "MINIO_SECRET_KEY=rsAuRptRwTTuSocsdBCRHIToldPkPefpb2Vl/ybG"
    volumes:
      - .data-docker/minio:/data

  app:
    build: .
    image: knesset-data/pipelines
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    environment:
      - "DPP_REDIS_HOST=redis"
      - "DPP_DB_ENGINE=postgresql://postgres:123456@db:5432/postgres"
      - "DPP_WORKER_CONCURRENCY=1"
    volumes:
      - .data-docker:/knesset/data
