{{ if .Values.enabled }}{{ if .Values.committeeMeetingAttendeesJob }}
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: committee-meeting-attendees
spec:
  schedule: {{ .Values.committeeMeetingAttendeesJob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: committee_meeting_attendees
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: {{ .Values.global.gkeNodePool | default "default-pool" | quote }}
          containers:
          - name: pipelines
            image: {{ .Values.committeeMeetingAttendeesJob.image | quote }}
            command:
            - bash
            - "-c"
            - |
              rm -f /pipelines/data/done &&\
              dpp run ./download/committees &&\
              dpp run ./join-committee-meetings &&\
              dpp run ./committee-meeting-attendees &&\
              touch /pipelines/data/done
            volumeMounts:
            - name: data
              mountPath: /pipelines/data
          - name: ops
            image: orihoch/sk8sops
            resources:
              requests:
                cpu: "0.01"
                memory: "150Mi"
            command:
            - bash
            - "-c"
            - |
              source ~/.bashrc
              ! gcloud config set project hasadna-oknesset \
                  && echo "Failed initialization" && exit 1
              ! gsutil ls -b gs://${GS_BUCKET_NAME}/ \
                  && ! gsutil mb gs://${GS_BUCKET_NAME}/ \
                      && echo "Failed to create bucket or authenticate with gs" && exit 1
              echo 'waiting for pipelines to complete'
              while ! [ -e /pipelines/data/done ]; do
                sleep 5
                echo .
              done
              rm -f /pipelines/data/done
              ! gsutil -m rsync -a public-read  -r /pipelines/data "gs://${GS_BUCKET_NAME}/" \
                  && echo "gsutil rsync failed" && exit 1
              echo "Great Success"
              exit 0
            env:
            - name: GS_BUCKET_NAME
              value: {{ .Values.committeeMeetingAttendeesJob.bucket | quote }}
            volumeMounts:
            - name: data
              mountPath: /pipelines/data
            - name: k8s-ops
              mountPath: /k8s-ops
              readOnly: true
          volumes:
          - name: k8s-ops
            secret:
              secretName: ops
          - name: data
            emptyDir: {}
          restartPolicy: Never
{{ end }}{{ end }}
