{{ if .Values.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{.Values.name | default "app"}}-management
spec:
  replicas: 1
  strategy: {type: Recreate}
  template:
    metadata:
      labels:
        app: {{.Values.name | default "app"}}-management
    spec:
      containers:
      - name: {{.Values.name | default "app"}}-management
        image: {{.Values.image | default "orihoch/knesset-data-pipelines:latest" | quote}}
        args: ["management"]
        env:
{{ include "app-common-env" . | indent 8}}
        resources:
          requests:
            cpu: {{.Values.cpuRequests | default "0.05"}}
            memory: {{.Values.memoryRequests | default "10Mi" | quote}}
      {{ if not .Values.global.skipInitContainers }}
      initContainers:
      - name: postgresql-create-db
        image: sameersbn/postgresql:9.6-2
        command: ['bash', '-c', 'psql -h ${APP_DB_HOST} -U ${APP_DB_USER} -p ${APP_DB_PORT} -c "CREATE DATABASE ${APP_DB_NAME}" || true']
        env:
        - {name: APP_DB_HOST, valueFrom: {secretKeyRef: {name: {{.Values.global.secretEnvVars | quote}}, key: "APP_DB_HOST"}}}
        - {name: APP_DB_NAME, valueFrom: {secretKeyRef: {name: {{.Values.global.secretEnvVars | quote}}, key: "APP_DB_NAME"}}}
        - {name: APP_DB_USER, valueFrom: {secretKeyRef: {name: {{.Values.global.secretEnvVars | quote}}, key: "APP_DB_USER"}}}
        - {name: APP_DB_PORT, valueFrom: {secretKeyRef: {name: {{.Values.global.secretEnvVars | quote}}, key: "APP_DB_PORT"}}}
        - {name: PGPASSWORD, valueFrom: {secretKeyRef: {name: {{.Values.global.secretEnvVars | quote}}, key: "APP_DB_PASS"}}}
      {{ end }}
{{ end }}
